services:
  - type: web
    name: smart-home-backend
    env: node
    region: oregon
    plan: free
  buildCommand: "npm install && npm run build && npx prisma generate"
  startCommand: "npx prisma migrate deploy && npx prisma generate && npm run start:prod"
    envVars:
      - key: DATABASE_URL
        value: "${DATABASE_URL}"
      - key: JWT_SECRET
        value: "${JWT_SECRET}"
      - key: HASH_SALT
        value: "${HASH_SALT}"
      - key: SEED_ADMIN_EMAIL
        value: "${SEED_ADMIN_EMAIL}"
      - key: SEED_ADMIN_PASSWORD
        value: "${SEED_ADMIN_PASSWORD}"
    disk: 1024
    autoDeploy: true
    pullRequestPreviews: true
    healthCheckPath: /health
